@startuml
!pragma teoz true
title Alpaca Discovery Protocol example for LAN 192.168.0.0/24
participant "Client\n192.168.0.10" as Client
participant "Device 1\n192.168.0.100\nAlpaca Port 1111" as Device1
participant "Device 2\n192.168.0.200\nAlpaca Port 2222" as Device2

Client -> Device1 : Discovery Broadcast\nFrom: 192.168.0.10:12345 (random port)\nTo: 192.168.0.255:32227 (subnet broadcast address)\nUDP datagram: "alpacadiscovery1"
& Device1 -> Device2 : Received by all hosts

Device1 -> Client : Discovery Response\nFrom: 192.168.0.100:24824 (random port)\nTo: 192.168.0.10:12345 (directed packet)\nUDP datagram: "{"AlpacaPort": 1111}"
Device2 -> Client : Discovery Response\nFrom: 192.168.0.200:43624 (random port)\nTo: 192.168.0.10:12345 (directed packet)\nUDP datagram: "{"AlpacaPort": 2222}"
@enduml
